- name: gitignore inventory
  ansible.builtin.lineinfile:
    path: "{{playbook_dir}}/.gitignore"
    regexp: "^.pre/files/inventory/test"
    line: ".pre/files/inventory/test"
    create: true

- name: Copy .default inventory to test 
  ansible.builtin.copy:
    src: "inventory/.example/"
    dest: "{{role_path}}/files/inventory/test"
  when: test_inventory