- debug:
    msg: "{{virtual_env}}"

- name: SQL pip install
  include_tasks: "{{fn}}/Pip_install.yml"
  loop:
  - pymysql
  - sqlalchemy

- name: Web Scraping pip install
  include_tasks: "{{fn}}/Pip_install.yml"
  loop:
  - beautifulsoup4
  - lxml
  - selenium
  - sqlalchemy
  - webdriver-manager 

- name: Tesseract pip install
  include_tasks: "{{fn}}/Pip_install.yml"
  loop:
  - "{{tesseract_python_pkg}}"