# Use:
# ansible-playbook prod.yml --tags pre
# ansible-playbook prod.yml --tags init

- hosts: localhost
  tags: [ pre, git]
  vars:
    src: ""
    repo: []

  tasks:
  - debug:
      msg: "{{item.name}}"
    loop: "{{repo}}"

  - name: Git checkout
    ansible.builtin.git:
      repo: "{{item.repo}}"
      dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/src/{{item.subdir}}{{item.name}}"
    loop: "{{repo}}"
