# Get repos
- name: dev.yml
  ansible.builtin.import_playbook: git/dev.yml

# Pre
- name: JupyterNotebook.ide( pre )
  ansible.builtin.import_playbook: "{{ lookup('ansible.builtin.env', 'HOME') }}/src/vpn/JupyterNotebook.ide/src/ansible/pre.yml"

- name: WebScraper.AI( pre )
  ansible.builtin.import_playbook: "{{ lookup('ansible.builtin.env', 'HOME') }}/src/vpn/WebScraper.AI/src/ansible/pre.yml"

# Init
- hosts: localhost
  tasks:
  - name: Init submodule dev.yml
    ansible.builtin.shell: ansible-playbook init/dev.yml
