# Use:
#   ansible-playbook ava.yml --tags dev
#   ansible-playbook ava.yml --tags test
#   ansible-playbook ava.yml --tags prod

#--------------------------------------------
# Get repos
- name: dev.yml
  ansible.builtin.import_playbook: git/dev.yml
  tags: [dev, never]

- name: test.yml
  ansible.builtin.import_playbook: git/test.yml
  tags: [test, never]

- name: prod.yml
  ansible.builtin.import_playbook: git/prod.yml
  tags: [prod, never]

#--------------------------------------------
# Init submodule
- hosts: localhost
  tasks:
  - name: Init submodule dev.yml
    ansible.builtin.shell: ansible-playbook init/dev.yml
    tags: [dev, never]

#  - name: Init submodule test.yml
#    ansible.builtin.shell: ansible-playbook init/test.yml
#    tags: [test, never]
#
#  - name: Init submodule prod.yml
#    ansible.builtin.shell: ansible-playbook init/prod.yml
#    tags: [prod, never]

# Debug: This is not going to have any output. Run them individually by hand if you need to debug!
