# Use:
#   ansible-playbook ava.yml --tags dev
#   ansible-playbook ava.yml --tags test
#   ansible-playbook ava.yml --tags prod

#--------------------------------------------
# Get repos
- name: dev.yml
  ansible.builtin.import_playbook: git/dev.yml
  tags: [dev, never]

- name: test.yml
  ansible.builtin.import_playbook: git/test.yml
  tags: [test, dev, never]

- name: prod.yml
  ansible.builtin.import_playbook: git/prod.yml
  tags: [prod, dev, never]

#--------------------------------------------
# Init submodules
- hosts: localhost
  tasks:
  - name: init/dev.yml
    ansible.builtin.shell: ansible-playbook init/dev.yml
    tags: [dev, never]

  - name: init/test.yml
    ansible.builtin.shell: ansible-playbook init/test.yml
    tags: [test, dev, never]

  - name: init/prod.yml
    ansible.builtin.shell: ansible-playbook init/prod.yml
    tags: [prod, dev, never]

# Debug: This is not going to have any output. Run them individually by hand if you need to debug!
