- name: create library dir
  ansible.builtin.file:
    path: "{{playbook_dir}}/library"
    state: directory

- name: gitignore library
  ansible.builtin.lineinfile:
    path: "{{item}}"
    regexp: "^library"
    line: "library"
    create: true
  loop:
  - "{{playbook_dir}}/.gitignore"

- name: link Libraries
  ansible.builtin.file:
    src: "{{git_dir}}/{{item.git}}/{{item.path}}/{{item.name}}"
    dest: "{{playbook_dir}}/library/{{item.name}}"
    state: link
  loop: "{{library}}"